version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]

  backend:
    build: ./backend
    env_file: .env.example
    depends_on: [db]
    ports: ["${BACKEND_PORT}:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./worker
    env_file: .env.example
    depends_on: [backend]
    command: python -m worker

  frontend:
    build: ./frontend
    env_file: .env.example
    depends_on: [backend]
    ports: ["${FRONTEND_PORT}:3000"]
    command: npm run dev

volumes:
  db_data:
