services:
- type: web
  name: sticker-dashboard
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  plan: free
  autoDeploy: true
  envVars:
    - key: APP_PASSWORD
      generateValue: true
    - key: SESSION_SECRET
      generateValue: true
  disk:
    name: data
    mountPath: /opt/render/project/src/data
    sizeGB: 1
